// Copyright (c) 2011 The WebM project authors. All Rights Reserved.
//
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file in the root of the source
// tree. An additional intellectual property rights grant can be found
// in the file PATENTS.  All contributing project authors may
// be found in the AUTHORS file in the root of the source tree.

#ifndef WEBMIDS_HPP
#define WEBMIDS_HPP

namespace mkvmuxer
{

enum MkvId {
  kMkvEBML                    = 0x1A45DFA3,
  kMkvEBMLVersion             = 0x4286,
  kMkvEBMLReadVersion         = 0x42F7,
  kMkvEBMLMaxIDLength         = 0x42F2,
  kMkvEBMLMaxSizeLength       = 0x42F3,
  kMkvDocType                 = 0x4282,
  kMkvDocTypeVersion          = 0x4287,
  kMkvDocTypeReadVersion      = 0x4285,
  //  CRC_32   = 0xBF,
  kMkvVoid                    = 0xEC,
  kMkvSignatureSlot           = 0x1B538667,
  kMkvSignatureAlgo           = 0x7E8A,
  kMkvSignatureHash           = 0x7E9A,
  kMkvSignaturePublicKey      = 0x7EA5,
  kMkvSignature               = 0x7EB5,
  kMkvSignatureElements       = 0x7E5B,
  kMkvSignatureElementList    = 0x7E7B,
  kMkvSignedElement           = 0x6532,
  //segment
  kMkvSegment                 = 0x18538067,
  //Meta Seek Information
  kMkvSeekHead                = 0x114D9B74,
  kMkvSeek                    = 0x4DBB,
  kMkvSeekID                  = 0x53AB,
  kMkvSeekPosition            = 0x53AC,
  //Segment Information
  kMkvInfo                    = 0x1549A966,
  //  SegmentUID   = 0x73A4,
  //  SegmentFilename   = 0x7384,
  //  PrevUID   = 0x3CB923,
  //  PrevFilename   = 0x3C83AB,
  //  NextUID   = 0x3EB923,
  //  NextFilename   = 0x3E83BB,
  //  SegmentFamily   = 0x4444,
  //  ChapterTranslate   = 0x6924,
  //  ChapterTranslateEditionUID   = 0x69FC,
  //  ChapterTranslateCodec   = 0x69BF,
  //  ChapterTranslateID   = 0x69A5,
  kMkvTimecodeScale           = 0x2AD7B1,
  kMkvDuration                = 0x4489,
  kMkvDateUTC                 = 0x4461,
  //  Title   = 0x7BA9,
  kMkvMuxingApp               = 0x4D80,
  kMkvWritingApp              = 0x5741,
  //Cluster
  kMkvCluster                 = 0x1F43B675,
  kMkvTimecode                = 0xE7,
  //  SilentTracks   = 0x5854,
  //  SilentTrackNumber   = 0x58D7,
  //  Position   = 0xA7,
  kMkvPrevSize                = 0xAB,
  kMkvBlockGroup              = 0xA0,
  kMkvBlock                   = 0xA1,
  //  BlockVirtual   = 0xA2,
  //  BlockAdditions   = 0x75A1,
  //  BlockMore   = 0xA6,
  //  BlockAddID   = 0xEE,
  //  BlockAdditional   = 0xA5,
  kMkvBlockDuration           = 0x9B,
  //  ReferencePriority   = 0xFA,
  kMkvReferenceBlock          = 0xFB,
  //  ReferenceVirtual   = 0xFD,
  //  CodecState   = 0xA4,
  //  Slices   = 0x8E,
  //  TimeSlice   = 0xE8,
  kMkvLaceNumber              = 0xCC,
  //  FrameNumber   = 0xCD,
  //  BlockAdditionID   = 0xCB,
  //  MkvDelay   = 0xCE,
  //  Cluster_Duration   = 0xCF,
  kMkvSimpleBlock             = 0xA3,
  //  EncryptedBlock   = 0xAF,
  //Track
  kMkvTracks                  = 0x1654AE6B,
  kMkvTrackEntry              = 0xAE,
  kMkvTrackNumber             = 0xD7,
  kMkvTrackUID                = 0x73C5,
  kMkvTrackType               = 0x83,
  kMkvFlagEnabled             = 0xB9,
  kMkvFlagDefault             = 0x88,
  kMkvFlagForced              = 0x55AA,
  kMkvFlagLacing              = 0x9C,
  //  MinCache   = 0x6DE7,
  //  MaxCache   = 0x6DF8,
  kMkvDefaultDuration         = 0x23E383,
  //  TrackTimecodeScale   = 0x23314F,
  //  TrackOffset   = 0x537F,
  //  MaxBlockAdditionID   = 0x55EE,
  kMkvName                    = 0x536E,
  kMkvLanguage                = 0x22B59C,
  kMkvCodecID                 = 0x86,
  kMkvCodecPrivate            = 0x63A2,
  kMkvCodecName               = 0x258688,
  //  AttachmentLink   = 0x7446,
  //  CodecSettings   = 0x3A9697,
  //  CodecInfoURL   = 0x3B4040,
  //  CodecDownloadURL   = 0x26B240,
  //  CodecDecodeAll   = 0xAA,
  //  TrackOverlay   = 0x6FAB,
  //  TrackTranslate   = 0x6624,
  //  TrackTranslateEditionUID   = 0x66FC,
  //  TrackTranslateCodec   = 0x66BF,
  //  TrackTranslateTrackID   = 0x66A5,
  //video
  kMkvVideo                   = 0xE0,
  kMkvFlagInterlaced          = 0x9A,
  //  StereoMode   = 0x53B8,
  kMkvPixelWidth              = 0xB0,
  kMkvPixelHeight             = 0xBA,
  kMkvPixelCropBottom         = 0x54AA,
  kMkvPixelCropTop            = 0x54BB,
  kMkvPixelCropLeft           = 0x54CC,
  kMkvPixelCropRight          = 0x54DD,
  kMkvDisplayWidth            = 0x54B0,
  kMkvDisplayHeight           = 0x54BA,
  kMkvDisplayUnit             = 0x54B2,
  kMkvAspectRatioType         = 0x54B3,
  //  ColourSpace   = 0x2EB524,
  //  GammaValue   = 0x2FB523,
  kMkvFrameRate               = 0x2383E3,
  //end video
  //audio
  kMkvAudio                   = 0xE1,
  kMkvSamplingFrequency       = 0xB5,
  kMkvOutputSamplingFrequency = 0x78B5,
  kMkvChannels = 0x9F,
  //  ChannelPositions = 0x7D7B,
  kMkvBitDepth                = 0x6264,
  //end audio
  //content encoding
  //  ContentEncodings = 0x6d80,
  //  ContentEncoding = 0x6240,
  //  ContentEncodingOrder = 0x5031,
  //  ContentEncodingScope = 0x5032,
  //  ContentEncodingType = 0x5033,
  //  ContentCompression = 0x5034,
  //  ContentCompAlgo = 0x4254,
  //  ContentCompSettings = 0x4255,
  //  ContentEncryption = 0x5035,
  //  ContentEncAlgo = 0x47e1,
  //  ContentEncKeyID = 0x47e2,
  //  ContentSignature = 0x47e3,
  //  ContentSigKeyID = 0x47e4,
  //  ContentSigAlgo = 0x47e5,
  //  ContentSigHashAlgo = 0x47e6,
  //end content encoding
  //Cueing Data
  kMkvCues                    = 0x1C53BB6B,
  kMkvCuePoint                = 0xBB,
  kMkvCueTime                 = 0xB3,
  kMkvCueTrackPositions       = 0xB7,
  kMkvCueTrack                = 0xF7,
  kMkvCueClusterPosition      = 0xF1,
  kMkvCueBlockNumber          = 0x5378,
  //  CueCodecState = 0xEA,
  //  CueReference = 0xDB,
  //  CueRefTime = 0x96,
  //  CueRefCluster = 0x97,
  //  CueRefNumber = 0x535F,
  //  CueRefCodecState = 0xEB,
  //Attachment
  //  Attachments = 0x1941A469,
  //  AttachedFile = 0x61A7,
  //  FileDescription = 0x467E,
  //  FileName = 0x466E,
  //  FileMimeType = 0x4660,
  //  FileData = 0x465C,
  //  FileUID = 0x46AE,
  //  FileReferral = 0x4675,
  //Chapters
  //  Chapters = 0x1043A770,
  //  EditionEntry = 0x45B9,
  //  EditionUID = 0x45BC,
  //  EditionFlagHidden = 0x45BD,
  //  EditionFlagDefault = 0x45DB,
  //  EditionFlagOrdered = 0x45DD,
  //  ChapterAtom = 0xB6,
  //  ChapterUID = 0x73C4,
  //  ChapterTimeStart = 0x91,
  //  ChapterTimeEnd = 0x92,
  //  ChapterFlagHidden = 0x98,
  //  ChapterFlagEnabled = 0x4598,
  //  ChapterSegmentUID = 0x6E67,
  //  ChapterSegmentEditionUID = 0x6EBC,
  //  ChapterPhysicalEquiv = 0x63C3,
  //  ChapterTrack = 0x8F,
  //  ChapterTrackNumber = 0x89,
  //  ChapterDisplay = 0x80,
  //  ChapString = 0x85,
  //  ChapLanguage = 0x437C,
  //  ChapCountry = 0x437E,
  //  ChapProcess = 0x6944,
  //  ChapProcessCodecID = 0x6955,
  //  ChapProcessPrivate = 0x450D,
  //  ChapProcessCommand = 0x6911,
  //  ChapProcessTime = 0x6922,
  //  ChapProcessData = 0x6933,
  //Tagging
  //  Tags = 0x1254C367,
  //  Tag = 0x7373,
  //  Targets = 0x63C0,
  //  TargetTypeValue = 0x68CA,
  //  TargetType = 0x63CA,
  //  Tagging_TrackUID = 0x63C5,
  //  Tagging_EditionUID = 0x63C9,
  //  Tagging_ChapterUID = 0x63C4,
  //  AttachmentUID = 0x63C6,
  //  SimpleTag = 0x67C8,
  //  TagName = 0x45A3,
  //  TagLanguage = 0x447A,
  //  TagDefault = 0x4484,
  //  TagString = 0x4487,
  //  TagBinary = 0x4485,
};

}  //end namespace mkvmuxer

#endif //WEBMIDS_HPP